version: '3.8'

services:
  stagehand:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stagehand-automation
    env_file:
      - ./backend/.env
    environment:
      - DISPLAY=:99
    volumes:
      - ./backend:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: sh -c "Xvfb :99 -screen 0 1920x1080x24 -nolisten tcp & sleep infinity"

# Usage:
# 1. Build: docker-compose build
# 2. Start: docker-compose up -d
# 3. Run test: docker-compose exec stagehand node runner.js --url "https://example.com" --test "Click the login button"
